const metadata = {
  directory: 'submission',
  url: 'https://intigral.net',
  identifierURL: 'https://intigral.net',
  title: 'Younes Alturkey | Intigral',
  description: `Based in Riyadh and Dubai, Intigral is the Media and Advertising arm of stc, and MENA’s leading provider of digital entertainment, sports, and media services via its market-leading and award-winning solutions, stc tv, Jawwy TV and Dawri Plus.`,
  subject: `Based in Riyadh and Dubai, Intigral is the Media and Advertising arm of stc, and MENA’s leading provider of digital entertainment, sports, and media services via its market-leading and award-winning solutions, stc tv, Jawwy TV and Dawri Plus.`,
  copyright: 'Intigral',
  language: 'en',
  robots: 'all',
  icon: '/favicon.png',
  themeColor: '#303546',
  generator: 'Intigral',
  designer: 'Intigral',
  applicationName: 'Younes Alturkey Assignment',
  referrer: 'origin-when-cross-origin',
  keywords: [
    'Intigral',
    'Intigral by STC',
    'STC Group',
    'STC TV',
    'Jawwy TV',
    'STC',
  ],
  replyTo: 'info@intigral.net',
  owner: 'Intigral',
  authors: [
    {
      name: 'Intigral',
      email: 'info@intigral.net',
      url: 'https://intigral.net',
    },
  ],
  colorScheme: 'light',
  creator: 'Intigral',
  publisher: 'Intigral',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    title: 'Younes Alturkey | Intigral',
    description: `Based in Riyadh and Dubai, Intigral is the Media and Advertising arm of stc, and MENA’s leading provider of digital entertainment, sports, and media services via its market-leading and award-winning solutions, stc tv, Jawwy TV and Dawri Plus.`,
    url: 'https://intigral.net',
    siteName: 'Younes Alturkey | Intigral',
    images: [
      {
        key: 'md',
        url: `https://intigral.younes.ninja/images/og.jpg`,
        alt: 'Intigral logo in a banner',
        width: 800,
        height: 600,
      },
      {
        key: 'lg',
        url: `https://intigral.younes.ninja/images/og-alt.jpg`,
        width: 1800,
        height: 1600,
        alt: 'Intigral logo in a banner',
      },
    ],
    locale: 'en',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Younes Alturkey | Intigral',
    description: `Based in Riyadh and Dubai, Intigral is the Media and Advertising arm of stc, and MENA’s leading provider of digital entertainment, sports, and media services via its market-leading and award-winning solutions, stc tv, Jawwy TV and Dawri Plus.`,
    siteId: '@Intigral',
    creator: '@Intigral',
    creatorId: '@Intigral',
    images: [`https://intigral.younes.ninja/images/og.jpg`],
    domain: 'intigral.net',
    url: 'https://intigral.net',
  },
}

export default metadata
